### ISSUE TITLE
high pass filter use method request

### ISSUE THREAD

**Issue by boksili** [eripe970/go-dsp-utils#4] opened 2022-11-23 15:54 UTC
HI.
I am new in golang.

I want open file and do HPF and save the file after HPF.

the file format is
1 28.00000
2 29.00000
3 28.00000
4 30.00000
5 28.00000
.....
.....

it has two column
(time well_height)

the sample rate is 0.0166Hz (60 seconds interval well height recording)
It has very very long term noise more than 200 sec
So I want to High pass filter with cutoff frequency 0.005 Hz

I looked over your golang code very carefully with 1 week
but Still I failed with your code.

Is there any sample form with open file and do HPF and save to file with HPF results ?

please help me. I am graduate course student.

Thanks for all.

TaeRhee

**Comment by eripe970** [comment] 2022-11-23 17:02
Hey, 

Do you have any code example of what you are trying to do?

**Comment by boksili** [comment] 2022-11-24 02:55
This is what I am trying to do with HPF apply,
I am trouble with do file open and do HPF and  file save.

-----------------------
package main

import (
				"fmt"
				"github.com/eripe970/go-dsp-utils"
				"github.com/go-echarts/go-echarts/v2/charts"
				"github.com/go-echarts/go-echarts/v2/components"
				"github.com/go-echarts/go-echarts/v2/opts"
				"github.com/go-echarts/go-echarts/v2/types"
				"log"
				"net/http"
				"time"
				"github.com/mattetti/audio"
				"github.com/mattetti/audio/transforms/filters"
)

func main() {
		 http.HandleFunc("/", handler)
		 log.Fatal(http.ListenAndServe(":4000", nil))
}

func	handler(w http.ResponseWriter, _ *http.Request) {
				signal, _ := dsp.ReadSignalFile("examples/signals/tidal_sample_part.txt", 0.0166)
				
				plot1 := plotSignal(signal, opts.Title{
								Title:    "Original signal 60sec per 1 measure, Well-Height",
								Subtitle: signal.String(),
				})
				signalday := signal.Sample(86400 * time.Second)

				page := components.NewPage()
				page.AddCharts(
					plot1,
		
				)

				page.Render(w)
}

						
func (s *signal) HighPassFilter(curOffFreq float64) (*signal, error) {
		   buffer := audio.NewPCMFloatBuffer(s.Signal), &audio.Format{SampleRate: int(s.SampleRate)})
		   
		   err := filters.HighPass(buffer, cutOffFreq)

			if err != nil {
				return nil, err
			}

			return &Signal{
					SampleRate: s.SampleRate,
					Signal:     buffer.Floats,
			}, nil
}


func plotSignal(signal *dsp.Signal, title opts.Title) *charts.Line {
	x := make([]string, 0)
	y := make([]opts.LineData, 0)
	for i := 0; i < signal.Length(); i++ {
		x = append(x, fmt.Sprintf("%.3f", float64(i)/signal.SampleRate))
		y = append(y, opts.LineData{Value: signal.Signal[i], Symbol: "none"})
	}

	line := charts.NewLine()
	line.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{Theme: types.ThemeWonderland}),
		charts.WithYAxisOpts(opts.YAxis{Max: signal.Max(), Min: signal.Min(), SplitNumber: 10}),
		charts.WithXAxisOpts(opts.XAxis{SplitNumber: 10}),
		charts.WithTitleOpts(title))

	line.SetXAxis(x).AddSeries("data", y).SetSeriesOptions(
		charts.WithLineChartOpts(opts.LineChart{
			Smooth: true,
		}),
	)

	return line
}
------------------

**Comment by boksili** [comment] 2022-11-24 09:14
//** actually I do more about with this, But I still failed with plot4. 


package main

import (
	"fmt"
	"log"
	"net/http"
	"time"

	"github.com/eripe970/go-dsp-utils"
	"github.com/go-echarts/go-echarts/v2/charts"
	"github.com/go-echarts/go-echarts/v2/components"
	"github.com/go-echarts/go-echarts/v2/opts"
	"github.com/go-echarts/go-echarts/v2/types"
)

func main() {

	http.HandleFunc("/", handler)
	log.Fatal(http.ListenAndServe(":4000", nil))
}

func handler(w http.ResponseWriter, _ *http.Request) {

	// A-1. Read the original signal---------------------------
	signal1, _ := dsp.ReadSignalFile("./tidal_sample_part.txt", 0.016666)
	fmt.Println(signal1)
	plot1 := plotSignal(signal1, opts.Title{
		Title:    "original signal",
		Subtitle: signal1.String(),
	})
	//---------------------------------------------------------

	// A-2. sample the signal to 10s---------------------------
	signal_parts := signal1.Sample(86400 * time.Second)
	fmt.Println(signal_parts)
	plot2 := plotSignal(signal_parts, opts.Title{
		Title:    "original signal 86400 second length",
		Subtitle: signal_parts.String(),
	})
	//---------------------------------------------------------

	//A-3. normalized signal ----------------------------------
	normalized, _ := signal1.Normalize()
	plot3 := plotSignal(normalized, opts.Title{
		Title:    "normalized signal ",
		Subtitle: normalized.String(),
	})
	//-------------------------------------------------------

	// A-4. DO High pass filter-------------------------------
	filtered, _ := signal_parts.HighPassFilter(0.00005)
	plot4 := plotSignal(filtered, opts.Title{
		Title:    "filtered signal with 86400 sample",
		Subtitle: filtered.String(),
	})

	page := components.NewPage()
	page.AddCharts(
		plot1,
		plot2,
		plot3,
		plot4,
	)
	page.Render(w)
}

func plotSignal(signal *dsp.Signal, title opts.Title) *charts.Line {
	x := make([]string, 0)
	y := make([]opts.LineData, 0)
	for i := 0; i < signal.Length(); i++ {
		x = append(x, fmt.Sprintf("%.1f", float64(i)/signal.SampleRate))
		y = append(y, opts.LineData{Value: signal.Signal[i], Symbol: "none"})
	}

	line := charts.NewLine()
	line.SetGlobalOptions(
		charts.WithInitializationOpts(opts.Initialization{Theme: types.ThemeWonderland}),
		charts.WithYAxisOpts(opts.YAxis{Max: signal.Max(), Min: signal.Min(), SplitNumber: 10}),
		charts.WithXAxisOpts(opts.XAxis{SplitNumber: 10}),
		charts.WithTitleOpts(title))

	line.SetXAxis(x).AddSeries("data", y).SetSeriesOptions(
		charts.WithLineChartOpts(opts.LineChart{
			Smooth: true,
		}),
	)

	return line
}

**Comment by eripe970** [comment] 2022-11-24 13:15
What if you handle the error and print out what happens. I think you should handle all the errors instead of ignoring them to make sure it works the way it should. 

```
filtered, err := signal_parts.HighPassFilter(0.00005)
if err != nil {
  panic(err)
}
```

**Comment by boksili** [comment] 2022-11-24 14:03
That's good Idea. because I am sooo New with the Golang.
I will do right it a way

**Comment by boksili** [comment] 2022-11-24 14:16
Do I need  FFT before apply  this    

filtered, err := signal_parts.HighPassFilter(0.00005)           ?

Because It still does not work. I think the code was freezed during on the HighPassFilter .

**Comment by eripe970** [comment] 2022-11-24 16:46
Can you upload a full example, can try to run it on my machine. 

Freezed as it never finish?

**Comment by boksili** [comment] 2022-11-24 18:01
[anothertest.zip](https://github.com/eripe970/go-dsp-utils/files/10086700/anothertest.zip)
[1col_tidal_sample_part_2n.txt](https://github.com/eripe970/go-dsp-utils/files/10086703/1col_tidal_sample_part_2n.txt)

**Comment by boksili** [comment] 2022-11-24 18:05
I uploaded 'anothertest.go'   file  and the data to be imported  
'1col_tidal_sample_part_2n.txt' 

I think something wrong with the frequency part.

The data which I handle frequency zone is very low frequency ( sample rate 0.016666 Hz)

But the High pass filter was designed for audio with very high frequency like 40,000 Hz something, I presummed..

**Comment by eripe970** [comment] 2022-11-24 20:28
Think it’s should work for all frequencies. Do you get an error or can you describe what the problem is?

**Comment by boksili** [comment] 2022-11-25 01:38
I checked the filtered component.
It says, the filtered data was NaN.
...
fmt.Println("filtered:", filtered.Signal[0:10])
...

results ->  [ 0 NaN NaN NaN NaN NaN NaN ... ]

It looks like 'FIR.Sinc.HighPassCoefs()' related.. As I looked over it...until.

**Comment by sio4** [comment] 2022-11-25 09:28
Hi @eripe970, @boksili, I took a look into this issue today and I found the followings:

1. in the `Signal.HighPathFilter()`, it prepares a PCM buffer with an **integer-converted** sampling rate [1],
2. because the type of `SampleRate`, of the structure `Format`, is an integer. [2]
3. internally, `Sinc` structure has the same type of member `SamplingFreq`, which came from the same argument, [3]
4. and the value is finally used to calculate `HighPassCoefs()` but... 
5. the sampleRate float 0.016 already turned into integer 0, and it became the **divide by zero** causing NaN. [4]

The issue is that @boksili 's use case needs a frequency under 0, which is 0.01666, so in this use case, the audio module and your module can not be used with the float frequency under 1.

It seems like the solution requires the fix on the mattetti/audio first since this module depends on the code but not sure if the audio module is still active (I saw the last fix was in 2019)

The patches for this issue could be

```patch
--- a/filters.go
+++ b/filters.go
@@ -6,7 +6,7 @@ import (
 )
 
 func (s *Signal) LowPassFilter(cutOffFreq float64) (*Signal, error) {
-	buffer := audio.NewPCMFloatBuffer(s.Signal, &audio.Format{SampleRate: int(s.SampleRate)})
+	buffer := audio.NewPCMFloatBuffer(s.Signal, &audio.Format{SampleRate: s.SampleRate})
 
 	err := filters.LowPass(buffer, cutOffFreq)
 
@@ -21,7 +21,7 @@ func (s *Signal) LowPassFilter(cutOffFreq float64) (*Signal, error) {
 }
 
 func (s *Signal) HighPassFilter(cutOffFreq float64) (*Signal, error) {
-	buffer := audio.NewPCMFloatBuffer(s.Signal, &audio.Format{SampleRate: int(s.SampleRate)})
+	buffer := audio.NewPCMFloatBuffer(s.Signal, &audio.Format{SampleRate: s.SampleRate})
 
 	err := filters.HighPass(buffer, cutOffFreq)
 
```

for your module, and

```patch
diff --git a/dsp/filters/sinc.go b/dsp/filters/sinc.go
index 8653298..959f97e 100644
--- a/dsp/filters/sinc.go
+++ b/dsp/filters/sinc.go
@@ -14,7 +14,7 @@ import (
 // http://mathworld.wolfram.com/SincFunction.html
 type Sinc struct {
 	CutOffFreq   float64
-	SamplingFreq int
+	SamplingFreq float64
 	// Taps are the numbers of samples we go back in time when processing the sync function.
 	// The tap numbers will affect the shape of the filter. The more taps, the more
 	// shape but the more delays being injected.
diff --git a/pcm_buffer.go b/pcm_buffer.go
index e8cd49d..f53fbc8 100644
--- a/pcm_buffer.go
+++ b/pcm_buffer.go
@@ -31,7 +31,7 @@ type Format struct {
 	// NumChannels is the number of channels contained in the data
 	NumChannels int
 	// SampleRate is the sampling rate in Hz
-	SampleRate int
+	SampleRate float64
 	// BitDepth is the number of bits of data for each sample
 	BitDepth int
 	// Endianess indicate how the byte order of underlying bytes
```

for the audio module, but I didn't check the details or possible side effects.

[1] https://github.com/eripe970/go-dsp-utils/blob/4563116e558a502bd2ae4d840e62594992a4a538/filters.go#L24
[2] https://github.com/mattetti/audio/blob/c6aebeb78429d88ff11f1468dac519ead57e7196/pcm_buffer.go#L30:L39
[3] https://github.com/mattetti/audio/blob/c6aebeb78429d88ff11f1468dac519ead57e7196/dsp/filters/sinc.go#L15:L25
[4] https://github.com/mattetti/audio/blob/c6aebeb78429d88ff11f1468dac519ead57e7196/dsp/filters/sinc.go#L85

**Comment by eripe970** [comment] 2022-11-25 17:06
I can make the changes this weekend or feel free to open a PR! But seems complicated if we have a downstream dependency that isn’t working. Could one solution be just to multiply the frequency with 10k, do the filtering and then divide with 10k? Just to work around the issue with low frequencies.

**Comment by sio4** [comment] 2022-11-26 13:25
Yeah, applying multiplied values was one of my suggestions to @boksili in another communication channel. Actually, I am not fully sure about the internal details in the `audio` module but it seems that the hack works fine. Could you please take a look at the PR #5?

**Comment by eripe970** [comment] 2022-11-26 14:40
Merged the #5 should solve the issues here now?

**Comment by sio4** [comment] 2022-11-26 15:18
Thanks for the quick action on the PR! I just told @boksili about the update.

By the way, do you have any plan to tag versions so users can easily see which version they use?

**Comment by boksili** [comment] 2022-11-26 16:14
Thanks for the update. @eripe970 @sio4 
Thanks for the help !!!!!
I have confirmed that the filter part which I am currently working on it, is working successfully.

**Closed as completed** 2022-11-26 16:14 UTC

**Comment by eripe970** [comment] 2022-11-27 16:20
> By the way, do you have any plan to tag versions so users can easily see which version they use?

I haven't put any effort into this project for a while but guess that would have been better. Let's start doing it for the next change! But happy to see that some people are using it :)
